### ISSUE TITLE
Possible memory corruption problem in c encoder

### ISSUE THREAD

**Issue by Combustible** [TkTech/mutf8#3]
I believe (but can not prove directly) that the C mutf8 encoder sometimes must create and return invalid buffers that when used later trigger a segmentation fault... or maybe something is corrupted in the memory stack that causes the cpython allocator to fail later. I'm not sure.

I almost hate to report this because I'm not sure it's actually a problem caused by this package... But it only happens when I use the c-encoder specifically, like this: 
```
from mutf8.cmutf8 import encode_modified_utf8
from mutf8.mutf8 import decode_modified_utf8
```
To be clear it also happens if I use the cmutf8 library for both encode AND decode. But does not happen if I reverse these (c decode, python encode), or use the pure-python version for both. 

My hesitancy is that I haven't managed to actually crash in this module. The segfault happens elsewhere when manipulating strings. It's possible that using this module is just shifting the memory around in just the right way to trigger a crash caused by a bug elsewhere... 

For background, I am writing automation tools against data produced by Minecraft (Java, hence mutf8). Each player file is stored as a binary compressed format each containing thousands of individual mutf8-encoded strings, and there are thousands of such player files. I unpack these into python data structures and manipulate them using this mutf8 library (among other things). I've been trying to track down a segmentation fault being thrown by an incredibly obscure combination of player data processing, and the only common denominator seems to be using the c-accelerated mutf8 decoder. For now I can "fix" my problem by using the python encoder... but this code is somewhat performance sensitive so I'd prefer not to be stuck with that forever. 

I have some input data and a tool that can reproduce this consistently so I could test a fix easily, but our clunky software would likely be a pain to get running on a different system, and might not trigger the same crash just by luck. Ugh. 

I doubt this is useful, but here's the GDB backtrace and py-bt backtrace: 
https://cdn.discordapp.com/attachments/447933054317494283/925131702613966848/gdb_segmentation_fault_backtrace.txt

I am on python 3.6.9 and mutf8 1.0.5. Using Ubuntu 20.04 on an x86_64 Intel system.

**Comment by TkTech** [comment]
Unfortunately that backtrace isn't super useful, like you surmised. If it is a memory corruption issue you should try running with the debug allocator enabled (`PYTHONTRACEMALLOC=1` in your environment). I'll give the C encoder another look for something obvious, but if you can come up with a consistent reproduction that would be easiest.

**Comment by Combustible** [comment]
Is it possible that length * 2 is not actually enough memory? That would explain it - overwriting beyond the end of the buffer would cause this behavior (corrupting nearby heap allocated objects). I'll re-run with the PYTHONTRACEMALLOC

**Comment by Combustible** [comment]
Not sure what I'm looking for here actually - any advice for how to run this so that it will produce useful results?

I inserted these lines as close as possible to the place where it segfaults: 
```
     snapshot = tracemalloc.take_snapshot()
     top_stats = snapshot.statistics('lineno')
 
     print("[ Top 10 ]")
     for stat in top_stats[:10]:
         print(stat)
```

With output
```
[ Top 10 ]
/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/registry.py:102: size=16.3 MiB, count=123504, average=138 B
/usr/lib/python3.6/json/decoder.py:355: size=11.1 MiB, count=149096, average=78 B
/home/epic/automation/quarry/quarry/types/../../brigadier.py/brigadier/string_reader.py:200: size=5275 KiB, count=43926, average=123 B
<frozen importlib._bootstrap_external>:487: size=5019 KiB, count=51561, average=100 B
/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py:1393: size=4278 KiB, count=78697, average=56 B
/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py:1376: size=3909 KiB, count=27525, average=145 B
/home/epic/automation/quarry/quarry/types/../../brigadier.py/brigadier/string_reader.py:157: size=2984 KiB, count=55467, average=55 B
/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py:1253: size=2098 KiB, count=44745, average=48 B
/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py:459: size=1824 KiB, count=25750, average=73 B
/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/registry.py:176: size=967 KiB, count=3344, average=296 B
```

Haven't used this tool before, not sure exactly what use would be actually useful.

**Comment by TkTech** [comment]
You shouldn't need to change your code at all, you just want to trigger the segfault. Sorry, I'm so used to having a debug build of the interpreter I forgot some things aren't on by default. You also want:

`PYTHONMALLOC=debug PYTHONTRACEMALLOC=1 PYTHONFAULTHANDLER=1 python <your reproduction example>`

- `PYTHONMALLOC=debug` will switch to a debug allocator. It'll fill the memory with a bit pattern and look for over and under accesses.
- `PYTHONTRACEMALLOC=1` will help fill in _where_ allocations were made when the fault happens.
- `PYTHONFAULTHANDLER=1` will cause the interpreter to dump a trace when it dies to a fault (no need to open up gdb)

**Comment by Combustible** [comment]
This is really cool!

```
Debug memory block at address p=0x9843560: API 'm'
    14 bytes originally requested
    The 7 pad bytes at p-7 are FORBIDDENBYTE, as expected.
    The 8 pad bytes at tail=0x984356e are not all FORBIDDENBYTE (0xfb):
        at tail+0: 0x84 *** OUCH
        at tail+1: 0xe8 *** OUCH
        at tail+2: 0xa3 *** OUCH
        at tail+3: 0x9d *** OUCH
        at tail+4: 0xe5 *** OUCH
        at tail+5: 0x8c *** OUCH
        at tail+6: 0x85 *** OUCH
        at tail+7: 0xfb
    The block was made by call #26938610 to debug malloc/realloc.
    Data at p: e9 bb 91 e4 ba ba e6 8a ac e6 a3 ba e7 b5

Memory block allocated at (most recent call first):
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 462

Fatal Python error: bad trailing pad byte

Current thread 0x00007fac82511740 (most recent call first):
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 462 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 824 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 824 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 578 in <genexpr>
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 578 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 824 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 824 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 824 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 578 in <genexpr>
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 578 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 824 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 824 in to_bytes
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 1471 in save
  File "/home/epic/automation/utility_code/minecraft/player_dat_format/player.py", line 246 in save
  File "/home/epic/automation/utility_code/minecraft/world.py", line 203 in iter_players
  File "/home/epic/automation/utility_code/minecraft/world.py", line 227 in iter_players_parallel
  File "utility_code/weekly_update_player_data.py", line 95 in <module>
```

This still doesn't point to the encoder though. Any way to figure out what call `26938610` is doing? Fortunately it seems to be deterministic (same error run both times I tried)

**Comment by TkTech** [comment]
```
Memory block allocated at (most recent call first):
  File "/home/epic/automation/utility_code/lib_py3/../../quarry/quarry/types/nbt.py", line 462
 ```
 
 This is the line of interest, what's the code around `nbt.py` line 462? Is it calling the encoder/decoder?

**Comment by Combustible** [comment]
Oh cool. It is indeed: https://github.com/TeamMonumenta/quarry/blob/79bbb0d21de66639a379fb9f8f932892956a0105/quarry/types/nbt.py#L462
```
    def to_bytes(self):
        data = encode_modified_utf8(self.value)         <- 462
        return Buffer.pack('H', len(data)) + data
````

**Comment by TkTech** [comment]
Alright, so it is an encoder issue. Can you dump `self.value` and add it here? Looks like we are writing 7 bytes too far for what we've allocated.

**Comment by Combustible** [comment]
Awesome! Thanks a ton for your guidance. We finally have a reproducer: 
```
from mutf8.cmutf8 import encode_modified_utf8, decode_modified_utf8

str = '黑人抬棺組裝包'
encode_modified_utf8(str)

print("done")
```

In the event that github doesn't like this unicode either: 
https://cdn.discordapp.com/attachments/447933054317494283/925251494616387624/test.py

Running it on my system with the memory flags gets flagged by the debugger infrastructure
```
» PYTHONMALLOC=debug PYTHONTRACEMALLOC=1 PYTHONFAULTHANDLER=1 python3 test.py                                                                                      
Debug memory block at address p=0x2248490: API 'm'
    14 bytes originally requested
    The 7 pad bytes at p-7 are FORBIDDENBYTE, as expected.
    The 8 pad bytes at tail=0x224849e are not all FORBIDDENBYTE (0xfb):
        at tail+0: 0x84 *** OUCH
        at tail+1: 0xe8 *** OUCH
        at tail+2: 0xa3 *** OUCH
        at tail+3: 0x9d *** OUCH
        at tail+4: 0xe5 *** OUCH
        at tail+5: 0x8c *** OUCH
        at tail+6: 0x85 *** OUCH
        at tail+7: 0xfb
    The block was made by call #57018 to debug malloc/realloc.
    Data at p: e9 bb 91 e4 ba ba e6 8a ac e6 a3 ba e7 b5

Memory block allocated at (most recent call first):
  File "test.py", line 5

Fatal Python error: bad trailing pad byte

Current thread 0x00007f284cb6c740 (most recent call first):
  File "test.py", line 5 in <module>
[4]    25162 abort (core dumped)  PYTHONMALLOC=debug PYTHONTRACEMALLOC=1 PYTHONFAULTHANDLER=1 python3 test.py
```

**Comment by Combustible** [comment]
This thread has definitely been the highlight of my day. I've spent basically the last three days tracking this down and it's been really satisfying to have quick expert responses that narrowed this down so fast to the actual problem. I was honestly just expecting to throw my debugging away and be stuck with the python version forever, since I couldn't go any further. Will be useful to know about these features working with python native code in the future. Really fun. Thanks! 

I'm in no particular rush for a solution, just glad to have my debugging work go somewhere.

**Comment by TkTech** [comment]
Release 1.0.6 is building now and should resolve this issue. Thanks for the report and the reproduction.
